INSERT INTO public.update_log (title, body, type, created_at) VALUES 
('Novas Funções de Comunidade', 'Os usuários agora podem criar contas e se registrar no Glossário. Membros registrados também ganharam a capacidade de enviar sugestões de novos termos, votar nas opções listadas e interagir adicionando comentários nas traduções da comunidade.', 'app', '2026-03-30 10:00:00'),
('Organização Visual Expandida', E'Foram estruturadas e organizadas as novas categorias de glossário.\nImplementado também um novo sistema visual de selos (badges coloridos) que buscam facilitar e agilizar o entendimento sobre a oficialidade das traduções e o rigor exigido pela Artifício.', 'app', '2026-03-30 12:00:00'),
('Usabilidade no Tooltip de Rigor', E'Ajuste de experiência no selo "Tradução Rigor Artifício RPG": o tooltip agora permanece visível por até 2 segundos após o mouse sair, permitindo que o usuário mova o cursor e clique no link de referência sem o conteúdo desaparecer imediatamente.', 'app', '2026-03-30 16:38:00'),
('Correção de Caracteres Importados na Busca', E'Corrigido o tratamento de termos com entidades HTML oriundas da importação (ex.: `&amp;apos;`, `&amp;` e variantes), eliminando exibições quebradas como `&AMP;APOS;` e melhorando a precisão da pesquisa.', 'app', '2026-03-30 17:01:00'),
('Saneamento Definitivo da Base Legada', E'Criada a migration `database/migration_02_sanitize_legacy_entities.sql` para normalizar entidades HTML e sequências unicode no PostgreSQL (ex.: `\u0026amp;`, `&AMP`, `&#10;`) diretamente nas tabelas de termos e fontes, removendo o problema na origem dos dados.', 'app', '2026-03-30 17:22:00');

INSERT INTO public.update_log (title, body, type, created_at) VALUES
('Central de Notificações em Tema Claro', E'Migramos a Central de Notificações para o padrão visual light do sistema com inputs e selects em tema claro, além de refinamentos no painel de filtros. Também alinhamos labels e estados de campo na tela de Meu Perfil para melhorar consistência e legibilidade.', 'app', '2026-03-31 21:40:00');
