export const SYNC_FIELDS: Record<string, string[]> = {
  users: ['id', 'google_id', 'email', 'username', 'location', 'role', 'refresh_token', 'privacy_public', 'created_at', 'updated_at'],
  auth_providers: ['id', 'user_id', 'provider', 'provider_user_id', 'provider_data', 'created_at'],
  profiles: ['id', 'user_id', 'display_name', 'bio', 'avatar_url', 'languages', 'tags', 'created_at', 'updated_at'],
  player_profiles: ['user_id', 'experience_level', 'playstyle', 'preferred_days', 'preferred_time', 'pricing_preference', 'updated_at'],
  gm_profiles: ['id', 'user_id', 'slug', 'nickname', 'bio_long', 'avatar_url', 'banner_url', 'languages', 'specialties', 'badges', 'tables_count', 'avg_rating', 'reviews_count', 'discord_connected', 'discord_username', 'discord_id', 'covil_verified', 'covil_verified_at', 'covil_verified_by', 'experience_years', 'average_price', 'gm_style', 'tools', 'game_format', 'tagline', 'promo_badge_text', 'selling_points', 'closed_group_enabled', 'closed_group_systems', 'closed_group_description', 'closed_group_min_price_cents', 'preferred_vtt_platforms', 'contact_methods', 'created_at', 'updated_at'],
  user_preferences: ['id', 'user_id', 'systems', 'tags', 'languages', 'platforms', 'weekdays', 'created_at', 'updated_at'],
  user_links: ['id', 'user_id', 'url', 'type', 'title', 'description', 'embed_url', 'thumbnail_url', 'metadata_status', 'metadata_fetched_at', 'metadata_last_accessed_at', 'metadata_fail_count', 'metadata_next_retry_at', 'sort_order', 'created_at', 'updated_at'],
  user_systems: ['id', 'user_id', 'system_id', 'type', 'created_at'],
  tables: ['id', 'slug', 'gm_id', 'system_id', 'scenario_id', 'custom_scenario', 'title', 'description', 'cover_url', 'status', 'type', 'audience', 'age_rating', 'modality', 'vtt_platform_id', 'game_platform_custom', 'game_platform_legacy', 'game_platform', 'communication_platform_id', 'communication_platform', 'price_type', 'price_value', 'price_frequency', 'slots_total', 'slots_filled', 'slots_open', 'language', 'experience_level', 'table_level', 'starts_at', 'city', 'state', 'content_warnings', 'safety_tools', 'source_url', 'source_id', 'origin', 'featured', 'publisher_role', 'actual_gm_name', 'is_ddal', 'ddal_code', 'ddal_name', 'ddal_tier', 'ddal_season', 'ddal_duration', 'ddal_format', 'ddal_org_code', 'ddal_setting', 'ddal_rules_notes', 'is_covil', 'imported_expires_at', 'rules_notes', 'banner_url', 'banner_crop_data', 'master_display_name', 'campaign_length', 'level_range', 'billing_text', 'session_zero_free', 'synopsis', 'style_text', 'listing_excerpt', 'technical_requirements', 'requires_pc', 'requires_camera', 'requires_microphone', 'setting_name', 'setting_styles', 'style_tags', 'synopsis_narrative', 'benefits_text', 'features', 'table_gm_bio', 'created_at', 'updated_at'],
  table_contacts: ['id', 'table_id', 'channel', 'value', 'label', 'discord_server_url', 'sort_order', 'created_at'],
  table_schedules: ['id', 'table_id', 'day_of_week', 'start_time', 'end_time', 'frequency', 'slots_per_session', 'is_ongoing', 'notes', 'sort_order', 'created_at'],
  table_metrics: ['id', 'table_id', 'views_count', 'clicks_count', 'contacts_count', 'favorites_count', 'created_at', 'updated_at'],
  gm_profile_metrics: ['id', 'gm_profile_id', 'views_count', 'created_at', 'updated_at'],
  systems: ['id', 'name', 'name_pt', 'slug', 'description', 'parent_id', 'node_type', 'depth', 'path_slug', 'logo_filename', 'website_url', 'created_at'],
  system_aliases: ['id', 'system_id', 'alias', 'alias_slug', 'is_official', 'created_at'],
  system_suggestions: ['id', 'user_id', 'name', 'name_pt', 'node_type', 'parent_id', 'batch_id', 'batch_index', 'parent_suggestion_index', 'description', 'aliases', 'status', 'reviewed_by', 'reviewed_at', 'rejection_reason', 'user_notified', 'created_at', 'updated_at'],
  tags: ['id', 'name', 'slug', 'created_at'],
  platforms: ['id', 'name', 'slug', 'created_at'],
  scenarios: ['id', 'name', 'name_pt', 'slug', 'description', 'subgenres', 'created_at'],
  scenario_aliases: ['id', 'scenario_id', 'alias', 'alias_slug', 'is_official', 'created_at'],
  scenario_suggestions: ['id', 'user_id', 'name', 'name_pt', 'description', 'aliases', 'subgenres', 'status', 'reviewed_by', 'reviewed_at', 'rejection_reason', 'user_notified', 'created_at', 'updated_at'],
  vtt_platforms: ['id', 'name', 'slug', 'logo_filename', 'website_url', 'is_active', 'sort_order', 'created_at', 'updated_at'],
  vtt_platform_suggestions: ['id', 'suggested_name', 'suggested_by_user_id', 'table_id', 'status', 'admin_notes', 'created_at', 'reviewed_at', 'reviewed_by_user_id'],
  communication_platforms: ['id', 'name', 'slug', 'website_url', 'is_active', 'sort_order', 'created_at', 'updated_at'],
  setting_style_suggestions: ['id', 'setting_name', 'suggested_styles', 'created_at', 'updated_at'],
};
